<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>QuantumServer</AssemblyName>
    <RootNamespace></RootNamespace>
    <Version>2.0.0.5</Version>
    <AssemblyVersion>2.0.0.5</AssemblyVersion>
    <FileVersion>2.0.0.5</FileVersion>
    <InformationalVersion>2.0.0.5-stubs</InformationalVersion>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>
